import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from '@vercel/analytics/next';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// UNTUK SEO WEBSITE--------------------------------------------------------------
export const metadata: Metadata = {
  title: {
    default: 'Firs Office',
    template: "%s | First Office"
  },
  description: "Generated by create next app",
  keywords: [
    "office",
    "work from anything",
    "meetings",
    "aesthetic",
    "cozy",
    "clean"
  ],
  openGraph: {
    title: "First Office - work form anything",
    description: "boost your mood to work your job",
    url: "https://superofficeirul.vercel.app/",
    siteName: "First Office",
    images: [
      {
        url: "/assets/images/thumbnails/thumbnail-details-1.png",
        width: 1200,
        height: 630
      }
    ],
    type: "website"
  }
};
// UNTUK SEO WEBSITE--------------------------------------------------------------




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>

          {children}
          <Analytics />
      </body>
    </html>
  );
}
